services:
  mariadb:
    image: mariadb:11.7
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_DATABASE: my_database
    ports:
      - "3309:3306"

  postgres:
    image: ankane/pgvector
    environment:
        POSTGRES_DB: my_database
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - "5432:5432"
