services:
  mariadb:
    image: mariadb:11.7
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_DATABASE: my_database
    ports:
      - '3309:3306'

  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    environment:
        POSTGRES_DB: my_database
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - '5432:5432'

  meilisearch:
      image: getmeili/meilisearch:v1.15
      environment:
          MEILI_MASTER_KEY: '${MEILISEARCH_MASTER_KEY:-changeMe}'
      ports:
          - '7700:7700'

  qdrant:
      image: qdrant/qdrant
      environment:
          QDRANT__SERVICE__API_KEY: '${QDRAT_SERVICE_API_KEY:-changeMe}'
      ports:
          - '6333:6333'

  surrealdb:
      image: surrealdb/surrealdb:v2
      command: ['start', '--user', 'symfony', '--pass', 'symfony']
      environment:
          SURREAL_HTTP_MAX_KEY_BODY_SIZE: 49152
      ports:
          - '8000:8000'

  neo4j:
      image: neo4j
      environment:
          NEO4J_AUTH: 'neo4j/${NEO4J_PASSWORD:-symfonyai}'
      ports:
          - '7474:7474'
          - '7687:7687'

  typesense:
      image: typesense/typesense:29.0
      environment:
          TYPESENSE_API_KEY: '${TYPESENSE_API_KEY:-changeMe}'
          TYPESENSE_DATA_DIR: '/data'
      volumes:
          - typesense_data:/data
      ports:
          - '8108:8108'

volumes:
    typesense_data:
