name: Code Quality

on:
    push:
        paths-ignore:
            - 'src/*/doc/**'
            - 'src/**/*.md'
    pull_request:
        paths-ignore:
            - 'src/*/doc/**'
            - 'src/**/*.md'

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    cs-php:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'
                    tools: php-cs-fixer
            -   name: php-cs-fixer
                run: php-cs-fixer check --diff

    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-version: [ '8.2', '8.3', '8.4']
                dependency-version: ['']
                symfony-version: ['']
                minimum-stability: ['stable']
                include:
                    # lowest deps
                    -   php-version: '8.2'
                        dependency-version: 'lowest'
                    # LTS version of Symfony
                    -   php-version: '8.2'
                        symfony-version: '6.4.*'
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            - name: Configure environment
              run: |
                  echo COLUMNS=120 >> $GITHUB_ENV
                  echo COMPOSER_MIN_STAB='composer config minimum-stability ${{ matrix.minimum-stability || 'stable' }} --ansi' >> $GITHUB_ENV
                  echo COMPOSER_UP='composer update ${{ matrix.dependency-version == 'lowest' && '--prefer-lowest' || '' }} --no-progress --no-interaction --ansi' >> $GITHUB_ENV
                  echo COMPOSER_VALIDATE='composer validate --strict' >> $GITHUB_ENV
                  echo PHPSTAN='vendor/bin/phpstan' >> $GITHUB_ENV

                  PACKAGES=$(find src/ -mindepth 2 -type f -name composer.json -not -path "*/vendor/*" -printf '%h\n' | sed 's/^src\///' | grep -Ev "examples" | sort |  tr '\n' ' ')
                  echo "Packages: $PACKAGES"
                  echo "PACKAGES=$PACKAGES" >> $GITHUB_ENV

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.2'
                    tools: flex

            - name: Install root dependencies
              run: composer install

            - name: Build root packages
              run: php .github/build-packages.php

            - name: Run PHPStan on packages
              run: |
                  source .github/workflows/.utils.sh

                  echo "$PACKAGES" | xargs -n1 | parallel -j +3 "_run_task {} '(cd src/{} && $COMPOSER_MIN_STAB && $COMPOSER_UP && $COMPOSER_VALIDATE && $PHPSTAN)'"
